# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:
{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd.availableKernelModules = [
      "xhci_pci"
      "thunderbolt"
      "nvme"
      "usb_storage"
      "usbhid"
      "sd_mod"
    ];
    initrd.kernelModules = [ ];
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];
  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = [
      "size=10G"
      "mode=755"
    ];
  };

  fileSystems."/persist" = {
    neededForBoot = true;
    device = "/dev/disk/by-uuid/43a36076-3f80-4a3f-aedf-1e7ad8a610eb";
    fsType = "btrfs";
    options = [
      "noatime"
      "subvol=persist"
      "compress=zstd:1"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/43a36076-3f80-4a3f-aedf-1e7ad8a610eb";
    fsType = "btrfs";
    options = [
      "noatime"
      "subvol=home"
      "compress=zstd:1"
    ];
  };

  fileSystems."/nix" = {
    neededForBoot = true;
    device = "/dev/disk/by-uuid/43a36076-3f80-4a3f-aedf-1e7ad8a610eb";
    fsType = "btrfs";
    options = [
      "noatime"
      "subvol=nix"
      "compress=zstd:1"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/43a36076-3f80-4a3f-aedf-1e7ad8a610eb";
    fsType = "btrfs";
    neededForBoot = true;
    options = [
      "noatime"
      "subvol=log"
      "compress=zstd:1"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4264-642F";
    fsType = "vfat";
    options = [ "noatime" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/43257656-c6a0-41d6-806c-b10e66f53fe1"; }
    ];


  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
